//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomatedMonitoringSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EaxmResult
    {
        public long ExamTypeId { get; set; }
        public int MaskingId { get; set; }
        public long StudentId { get; set; }
        public decimal MarksOutOf { get; set; }
        public decimal ObtainMark { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
