//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomatedMonitoringSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfo
    {
        public long StudentId { get; set; }
        public int Roll { get; set; }
        public int Year { get; set; }
        public string Shift { get; set; }
        public long ClassId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public string Residential { get; set; }
    }
}
