//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomatedMonitoringSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vm_GetAllStudentInfo
    {
        public long StudentId { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public System.DateTime Birthday { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string Contact1 { get; set; }
        public string Contact2 { get; set; }
        public int Roll { get; set; }
        public string ClassName { get; set; }
        public string SectionName { get; set; }
        public string Shift { get; set; }
        public string Residential { get; set; }
    }
}
